#!/bin/bash
URL="http://kslweb1.spb.ctf.su/first/level7/"
HOST="kslweb1.spb.ctf.su"
Connection="close"

Cookies=''
for cook in {1..100}; do
        Cookies+="cookie$cook=value$cook; "
done
Cookies="${Cookies%; }"
curl -L "$URL" -H "Host: $HOST" \
-H "Connection: $Connection" \
-H "Upgrade-Insecure-Requests: 1" \
-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 YaBrowser/25.8.0.0 Safari/537.36" \
-H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" \
-H "Accept-Encoding: gzip, deflate" \
-H "Accept-Language: ru,en;q=0.9" \
-H "Cookie: $Cookies"
